Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CrudApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/StudentController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CrudApp.Controllers
{
    public class StudentController : Controller
    {
        CRUDEntities4 db = new CRUDEntities4();
        string[] AllowedExtensions = new string[] { ".jpg", ".gif", ".png" };
        // GET: Student
        public ActionResult Index()
        {
            //CRUDEntities4 getstd = new CRUDEntities4();
            //var std = db.Students.ToList();
            var std = db.Students
                      .ToList()
                      .Select(
                        s => new Student
                        {
                            StudentID = s.StudentID,
                            StudentName = s.StudentName,
                            Email = s.Email,
                            RegistrationNo = s.RegistrationNo,
                            Address = s.Address,
                            City = s.City,
                            Province = s.Province,
                            Picture = s.Picture
                        }
                     );
            //var std = getstd.Students.ToList().Select(s => new { s.StudentName, s.RegistrationNo, s.Province, s.City, s.Address, s.Email });
            return View(std);
        }

        [HttpGet]
        public ActionResult CreateStudent()
        {
            ViewBag.Province = GetProvince();
            ViewBag.City = GetCity();
            return View();
        }

        [HttpPost]
        public ActionResult CreateStudent(Student obj)
        {
            string[] ext = {".jpg",".png",".jpeg", ".gif" };

            ViewBag.Province = GetProvince();

            ViewBag.City = GetCity();

            if (obj.ImageFile != null)
            {
                string filename = Path.GetFileNameWithoutExtension(obj.ImageFile.FileName);

                string gid = Guid.NewGuid().ToString();

                string extension = Path.GetExtension(obj.ImageFile.FileName);

                var validExtention = ext.Contains(extension);

                if (!validExtention)
                {
                    ModelState.AddModelError("Picture", "Only image files are allowed. Please enter .jpg, .jpeg or .png file.");
                    return View(obj);
                }

                filename = filename + gid;

                filename = filename + extension;

                obj.Picture = "~/Images/" + filename;

                filename = Path.Combine(Server.MapPath("~/Images/"), filename);

                obj.ImageFile.SaveAs(filename);
            }

            if (ModelState.IsValid)
            {
                //db.Entry(obj).State = System.Data.Entity.EntityState.Added;

                db.Students.Add(obj);

                db.SaveChanges();

                return RedirectToAction("Index");
            }
           
            return View();
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var s = db.Students.Where(std => std.StudentID == id).ToList().FirstOrDefault();
            return View(s);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var editStd = db.Students.Where(s => s.StudentID == id).ToList().FirstOrDefault();
            //ViewBag.pName = editStd.Province.ProvinceName;
            //ViewBag.cName = editStd.City.CityName;
            ViewBag.Province = GetProvince();
            ViewBag.City = GetCity();
            //if (editStd != null)
            //{
            //    obj.Picture = editStd.Picture;
            //}
            //ViewBag.pName = GetProvinceName(editStd);
            //ViewBag.cName = GetCityName(editStd);
            return View(editStd); ;
        }

        [HttpPost]
        public ActionResult Edit(int id, Student obj)
        {
            string[] ext = { ".jpg", ".png", ".jpeg", ".gif" };

            var getStd = db.Students.Where(s => s.StudentID == id).ToList().FirstOrDefault();

            ViewBag.Province = GetProvince();

            ViewBag.City = GetCity();

            if(obj.ImageFile!=null)
            {
                string filename = Path.GetFileNameWithoutExtension(obj.ImageFile.FileName);

                string gid = Guid.NewGuid().ToString();

                string extension = Path.GetExtension(obj.ImageFile.FileName);

                var validExtention = ext.Contains(extension);

                if (!validExtention)
                {
                    ModelState.AddModelError("Picture", "Only image files are allowed. Please enter .jpg, .jpeg or .png file.");
                    return View(obj);
                }

                filename = filename + gid;

                filename = filename + extension;

                obj.Picture = "~/Images/" + filename;

                filename = Path.Combine(Server.MapPath("~/Images/"), filename);

                obj.ImageFile.SaveAs(filename);
            }

            if (ModelState.IsValid)
            {
                getStd.StudentName = obj.StudentName;

                getStd.RegistrationNo = obj.RegistrationNo;

                getStd.Email = obj.Email;

                getStd.Address = obj.Address;

                getStd.CityID = obj.CityID;

                getStd.ProvinceID = obj.ProvinceID;

                getStd.Picture = obj.Picture;

                db.Entry(getStd).State = System.Data.Entity.EntityState.Modified;

                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var getStd = db.Students.Where(s => s.StudentID == id).ToList().FirstOrDefault();
            return View(getStd);
        }

        [HttpPost]
        public ActionResult Delete(int id, Student obj)
        {
            var delStd = db.Students.Where(s => s.StudentID == id).ToList().FirstOrDefault();
            var imgpath = delStd.Picture;
            string path = Server.MapPath(imgpath);
            if (delStd != null)
            {
                db.Students.Remove(delStd);
                System.IO.File.Delete(path);
                //db.Entry(delStd).State = System.Data.Entity.EntityState.Deleted;
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public SelectList GetProvince()
        {
            //CRUDEntities4 p = new CRUDEntities4();
            var provinceList = db.Provinces.ToList();
            var provList = new SelectList(provinceList, "ProvinceID", "ProvinceName");
            return provList;
        }

        public SelectList GetCity()
        {
            //CRUDEntities4 c = new CRUDEntities4();
            var cityList = db.Cities.ToList();
            SelectList cList = new SelectList(cityList, "CityID", "CityName");
            return cList;
        }

    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Student/CreateStudent.cshtml
@model CrudApp.Student

@{
    ViewBag.Title = "CreateStudent";
}

<h2>CreateStudent</h2>


@using (Html.BeginForm("CreateStudent", "Student", FormMethod.Post, new { @class = "formn-horizontal", enctype = "multipart/form-data" }    ))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StudentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentName, "", new { @class = "text-danger" })
            </div>
        </div>  

        <div class="form-group">
            @Html.LabelFor(model => model.RegistrationNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegistrationNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegistrationNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Province, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="margin-top: 7px; width: 40%">
                @*@Html.DropDownListFor(model => model.Province, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.ProvinceID, (IEnumerable<SelectListItem>)ViewBag.Province as SelectList, "Select Province Name")     

                @Html.ValidationMessageFor(model => model.Province, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="margin-top: 6px">
                @*  @Html.DropDownListFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.CityID, (IEnumerable<SelectListItem>)ViewBag.City as SelectList, "Select City Name")
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="margin-top: 3px">
                <input type="file" name="ImageFile" value="Select File" style="margin-top: 2px" />
                @* <input type="button" name="selectFile" value="Select File"  style="background-color: darkslateblue; color: white"/> *@
                @*   @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })  *@
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Student/Delete.cshtml
@model CrudApp.Student

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StudentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.Picture)*@
            @if (Model != null)
            {
                <img style="width:250px; height:300px" src="@Url.Content(Model.Picture)" />
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City.CityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City.CityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Province.ProvinceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Province.ProvinceName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-default" /> |
    @Html.ActionLink("Back to List", "Index")
</div>
    }
</div>

Views/Student/Details.cshtml
@model CrudApp.Student

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StudentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.Picture)*@
            @if(Model.Picture!=null)
            {
                <img style="width:250px; height:300px" src="@Url.Content(Model.Picture)" />
            }
            else
            {
                <p><strong>There is no image to show against that student. </strong></p>   
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City.CityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City.CityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Province.ProvinceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Province.ProvinceName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.StudentID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Student/Edit.cshtml
@model CrudApp.Student

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Student", FormMethod.Post, new { @class = "formn-horizontal", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StudentID)

        <div class="form-group">
            @Html.LabelFor(model => model.StudentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegistrationNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegistrationNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegistrationNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Province, "Province", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="margin-top: 7px; width: 40%">
                @*@Html.DropDownList("ProvinceID", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.DropDownListFor(model => model.ProvinceID, (IEnumerable<SelectListItem>)ViewBag.Province as SelectList, "Select Province Name")

                @Html.ValidationMessageFor(model => model.Province, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, "City", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="margin-top: 6px">
                @*@Html.DropDownList("CityID", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.DropDownListFor(model => model.CityID, (IEnumerable<SelectListItem>)ViewBag.City as SelectList, "Please select city")
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })*@

                @if (Model.Picture != null)
                {
                    <img style="width:250px; height:300px" src="@Url.Content(Model.Picture)" />
                }
                <input type="file" name="ImageFile" value="Select File" style="margin-top: 10px" />
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Student/Index.cshtml
@model IEnumerable<CrudApp.Student>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "CreateStudent")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StudentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegistrationNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City.CityName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Province.ProvinceName)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Picture)
        </th>*@

        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.StudentName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.RegistrationNo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Address)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.City.CityName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Province.ProvinceName)
    </td>
    @*<td>
        @Html.DisplayFor(modelItem => item.Picture)
    </td>*@
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.StudentID }) |
        @Html.ActionLink("Details", "Details", new { id = item.StudentID }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.StudentID })
    </td>
</tr>
}

</table>